sudo: false
language: ruby
rvm: 2.4.1
deploy:
  provider: heroku
  api_key:
    secure: yECzr8NrY4d5NFRFCBlT2XKA84gidM25kw/yyzxtdmZrtkKOw9YtKQZIRE4lqfeq00TILEyhc/a80e9kh3ImEMIUSGKSoSVojTy1ebm7JR+1faGdJidG1oKVhVgxKAJ45TMKi72t6lWy2Q2n0XbMDnFRTP82d5XipC45gZ/J0yyVrKEQ8hmP8JkDIbe/L/zCIaeLlUpl2agm284fHCScAgp9AFbK+r430E+ZrsRT41K8YCBEj7t82WcQnGFti3hi67PXPO+e+Ji5U68JouujKy/DRIaZ1hkHeFbha0A3BvW//Z2pRyiTg/SYo2iCnsrQYOXKCi6sAeEurQdyxLm5wtEDuM9pmHEBXaAaTCG0TlJtr07GgoxUL2s2vglxUuryVNGAvLTgsQVWgCMmHrkTtvb/Lg7aXD36BVQ1KbGFtEQb1QaqS/oFUyY/OoSiurPP4IEB0DzQ8e9eIgIreOYEIMjoeinUUFJNZMEdB+sa/pJoT7DJNFeEA3OFJIrS/dVCtqdhwh/I2EizOVCpFILKVGxXQLxWpVi3BTdrCshSEE1BRXlds+IIZ8RsCeMYUqLRn4ErVmrHPJaf4n5ZU45xjSGEug1Kx+d3Jq1QdqgrhSjtkN1Kk1+adXGAH78Ltf5M53Qn6t9xHlU0kT6dU59CRu48YjF5zN1WrpXk1LxR6O0=
  app:
    master: soccer-danbuettner-net
  on:
    repo: Capncavedan/soccer.danbuettner.net
cache: bundler
